name: devbot: core
on:
  push:
    paths:
      - "devbot/**"
      - ".github/workflows/10_devbot_ci.yml"
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python devbot/jarvis_devbot.py
