name: CI (dev)
on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "dev" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Lint (best-effort)
        run: |
          python -m pip install ruff || true
          ruff --version || true
          ruff . || true
      - name: Build check (backend only smoke)
        run: |
          python -c "print('backend OK')"  # replace with real build/tests later
