name: CI (dev)
on:
  push:
    branches: [dev]
  workflow_dispatch:
jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Open PR from dev to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ci/dev-to-main
          title: "Promote dev → main"
          commit-message: "chore: promote dev to main"
          body: "Automated promotion from dev."
