name: DevBot Core CI (minimal)

on:
  push:
    branches:
      - main
      - dev
      - fix/**
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip requests pyyaml gitpython watchdog

      - name: Run DevBot self-check
        run: |
          echo "🧠 Running DevBot Core Check..."
          python3 devbot/jarvis_devbot.py --test
