name: DevBot Core CI (minimal)

on:
  push:
    paths:
      - "devbot/**"
      - ".github/workflows/devbot_ci.yml"
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml gitpython watchdog
      - name: Run self-check
        run: python devbot/jarvis_devbot.py --test
