name: DevBot Core CI (minimal)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml gitpython watchdog

      - name: Run Jarvis DevBot self-check
        run: |
          echo '🚀 Running Jarvis DevBot core test...'
          python devbot/jarvis_devbot.py --test

