name: Failsafe Auto-Repair

on:
  workflow_run:
    workflows:
      - DevBot Core CI (minimal)
      - Jarvis Maintenance Loop
    types:
      - completed

jobs:
  rerun_once:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check rerun flag
        id: check
        run: |
          FLAG=".github/.rerun_${{ github.event.workflow_run.id }}"
          if [ -f "$FLAG" ]; then
            echo "Already retried once — stopping."
            echo "retry=false" >> $GITHUB_OUTPUT
          else
            echo "retry=true" >> $GITHUB_OUTPUT
            touch "$FLAG"
          fi

      - name: Trigger rerun once
        if: steps.check.outputs.retry == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const wf_id = context.payload.workflow_run.id;
            await github.rest.actions.reRunWorkflowFailedJobs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: wf_id
            });
            console.log("✅ Triggered rerun once for failed workflow:", wf_id);

      - name: Log no-rerun case
        if: steps.check.outputs.retry == 'false'
        run: echo "⚠️  Rerun already attempted for this workflow. Manual review needed."
