name: Jarvis Tasks → PR

on:
  schedule: [{ cron: "*/5 * * * *" }]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  build_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml gitpython

      - name: Process jarvis tasks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPO_FULL: ${{ github.repository }}
        run: |
          python devbot/jarvis_devbot.py --process-issues
