name: Jarvis Phase 2 Upgrade

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  auto_maintain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml gitpython watchdog

      - name: Run Jarvis DevBot Maintenance
        run: |
          echo "🧠 Running Jarvis Phase 2 maintenance..."
          python devbot/jarvis_devbot.py --once
