name: Jarvis Tasks → Scaffold PR
on:
  schedule: [{ cron: "*/5 * * * *" }]
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
  issues: read
jobs:
  build_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip requests
      - name: Process issues labeled jarvis:task
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python devbot/jarvis_builder.py
