name: Jarvis Maintenance Loop (debug)

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:

jobs:
  maintain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show tree & Python
        run: |
          pwd || true
          find . -maxdepth 3 -type f | sort
          python --version
          which python

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml gitpython watchdog

      - name: Run once
        run: python devbot/jarvis_devbot.py --once
