name: Nightly self-check
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install --upgrade pip requests pyyaml gitpython watchdog
      - name: Run self-check
        id: selfcheck
        continue-on-error: true
        run: python devbot/jarvis_devbot.py
      - name: File issue on failure
        if: steps.selfcheck.outcome != 'success'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/JARVIS_FAILED.md
